spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.3.255.23:3306/egenecloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: develop
    password: develop
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
